### ISSUE TITLE
Slack Message Contains No Data

### ISSUE THREAD

**Issue by goldsteindavid** [cameronoxley/Newman-to-Slack#7]
I found this script and thought it would be great to integrate to my process. It's working fine in that it's running my Postman/Newman scripts but the output to Slack is blank. I'm only getting some backticks as follows: ``````

**Comment by cameronoxley** [comment]
Please check with new release

**Comment by nugi-nn** [comment]
Now i using node.js v10+ and newman v4+ ,then i found  `````` on my slack .
so i must downgrade node.js & newman version ?
