### ISSUE TITLE
Is loading a CSV file supported?

### ISSUE THREAD

**Issue by lucascallado** [cameronoxley/Newman-to-Slack#9]
I tried using the newman -d command to bring a CSV file but it states that -d is unsupported. 
Is there a workaround to load a CSV file to the test?

**Comment by cameronoxley** [comment]
Hi @lucascallado: The `-a` command passes additional arguments through the script directly to newman.

For example: `Newman-to-Slack.sh -c "https://www.getpostman.com/collections/" -w "https://hooks.slack.com/services/url" -a "--ignore-redirects"` where --ignore-redirects is a newman argument.

You should be able to run the -d argument like this: `Newman-to-Slack.sh -c "https://www.getpostman.com/collections/" -w "https://hooks.slack.com/services/url" -a "-d file.csv"`
